server {
    listen 5173;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://mamaspantryapi.babafemicodes.dev/api/;
        proxy_set_header Host mamaspantryapi.babafemicodes.dev;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
